name: GNU/Linux build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install meshview dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgl-dev libglu1-mesa-dev libglut-dev libpng-dev libjpeg-dev libxmu-dev
        git clone https://github.com/jtsiomb/libimago
        cd libimago
        ./configure
        make
        sudo make install

    - name: configure
      run: ./configure --enable-opt --prefix=$(pwd)/staging/meshfile-gnulinux

    - name: build
      run: make

    - name: build meshview
      run: make meshview

    - name: build meshconv
      run: make meshconv

    - name: stage install
      run: |
        make install-all
        tree staging

    - uses: actions/upload-artifact@v4
      with:
          name: meshfile-gnulinux
          path: staging

# vi:ts=2 sts=2 sw=2 expandtab:
